module.exports = {
	COMMUNITY_CHAT: "COMMUNITY_CHAT",
	USER_CONNECTED: "USER_CONNECTED",
	USER_DISCONNECTED: "USER_DISCONNECTED",
	VERIFY_USER: "VERIFY_USER",
	LOGOUT: "LOGOUT",
	NOTIFICATION: "NOTFICATION",
	RECEIVEQUICKHELP: "RECEIVEQUICKHELP",
	QUICKHELPRESPONSE: "QUICKHELPRESPONSE",
	RELOAD_DATA: "RELOAD_DATA"
}